remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

# General infos
title: Executable Scenario
logo: assets/img/sesame_logo_tagline.svg
description: The Executable Scenario (ExSce) Work Package of the SESAME project.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
