remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

# General infos
title: Executable Scenario
logo: assets/img/sesame_logo_tagline.svg
project_url: https://www.sesame-project.org/
description: The Executable Scenario (ExSce) Work Package of the SESAME project.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

github:
  owner_name:  SECORO Group at the University of Bremen 
  owner_url: https://github.com/secorolab