remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

# General infos
title: Executable Scenario
logo: assets/img/sesame_logo_tagline.svg
description: Landing page for the models and toolings developed within the Executable Scenario (ExSce) Work Package.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
