remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

# General infos
title: ExSce Workbench
logo: /assets/img/sesame_logo_tagline.svg
description: Models and metamodels developed for the Executable Scenario Workbench
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
